import { useMemo, useState } from "react";
import { GameShell } from "../games/GameShell";
import {
  chunk,
  isSolved,
  neighbours,
  scrambleSlidingPuzzle,
} from "../lib/mixgap";
import type { MixGapSet } from "../types";

/**
 * TaskMagic's Tile 3×3 / 4×4 / 5×5: the passage is cut into size²−1 chunks
 * laid out with one empty cell, and "any tile can be dragged into the empty
 * space" — a sliding puzzle. Only tiles orthogonally adjacent to the gap can
 * move, and the start position is generated by shuffling legal moves so it
 * is always solvable.
 */
export function Tile({ set, size }: { set: MixGapSet; size: number }) {
  const cells = size * size;
  const chunks = useMemo(() => chunk(set.text, cells - 1), [set.text, cells]);
  const [board, setBoard] = useState<number[]>(() => scrambleSlidingPuzzle(size));
  const [moves, setMoves] = useState(0);
  const [peeking, setPeeking] = useState(false);

  const blankValue = cells - 1;
  const blankAt = board.indexOf(blankValue);
  const solved = isSolved(board);

  function slide(position: number) {
    if (solved) return;
    if (!neighbours(blankAt, size).includes(position)) return;
    setBoard((prev) => {
      const next = [...prev];
      next[blankAt] = next[position];
      next[position] = blankValue;
      return next;
    });
    setMoves((m) => m + 1);
  }

  function restart() {
    setBoard(scrambleSlidingPuzzle(size));
    setMoves(0);
  }

  const movable = new Set(neighbours(blankAt, size));

  return (
    <GameShell
      setId={set.id}
      setTitle={set.title}
      gameName={`Tile ${size}×${size}`}
      status={<div className="text-sm text-slate-200">Moves: {moves}</div>}
    >
      <div className="flex flex-col items-center gap-4 w-full max-w-3xl">
        {solved ? (
          <div className="text-center flex flex-col items-center gap-3">
            <div className="text-2xl font-bold">Text rebuilt! 🎉</div>
            <div className="text-slate-600">In {moves} moves.</div>
            <button
              onClick={restart}
              className="rounded-lg bg-cga-600 hover:bg-cga-700 text-white font-semibold px-6 py-3"
            >
              Shuffle again
            </button>
          </div>
        ) : (
          <button
            onClick={() => setPeeking((p) => !p)}
            className="text-sm text-slate-500 underline"
          >
            {peeking ? "Hide the original" : "Show the original"}
          </button>
        )}

        {peeking && !solved && (
          <p className="bg-white rounded-lg shadow p-4 text-sm text-slate-600 w-full">
            {set.text}
          </p>
        )}

        <div
          className="grid gap-1.5 w-full"
          style={{ gridTemplateColumns: `repeat(${size}, minmax(0, 1fr))` }}
        >
          {board.map((value, position) => {
            const isBlank = value === blankValue;
            const canMove = movable.has(position) && !solved;
            return (
              <button
                key={position}
                onClick={() => slide(position)}
                disabled={isBlank || !canMove}
                className={`min-h-24 rounded-lg p-2 text-sm text-left align-top transition-colors ${
                  isBlank
                    ? "bg-slate-200/60 border-2 border-dashed border-slate-300"
                    : solved
                      ? "bg-leaf-100 border border-leaf-400"
                      : canMove
                        ? "bg-white shadow hover:bg-cga-50 border-2 border-cga-300 cursor-pointer"
                        : "bg-white shadow border border-slate-200"
                }`}
              >
                {!isBlank && chunks[value]}
              </button>
            );
          })}
        </div>

        {!solved && (
          <p className="text-xs text-slate-400">
            Click a tile next to the empty square to slide it across.
          </p>
        )}
      </div>
    </GameShell>
  );
}
